# Generated by Django 6.0.4 on 2026-04-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_type', 'institution_name', 'name']},
        ),
        migrations.AddField(
            model_name='account',
            name='account_number_last4',
            field=models.CharField(blank=True, help_text='Optional last 4 digits only', max_length=4),
        ),
        migrations.AddField(
            model_name='account',
            name='billing_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Credit card billing statement day', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Only used for credit cards', max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Credit card payment due day', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='institution_name',
            field=models.CharField(blank=True, help_text='Example: BDO, BPI, GCash, Maya, UnionBank', max_length=100),
        ),
    ]
