# Generated by Django 6.0.4 on 2026-04-26 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_recurringbill_bill_recurring_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_bills', to='finance.transaction'),
        ),
    ]
