# Generated by Django 5.2.13 on 2026-04-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_account_id_alter_bill_id_alter_budget_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneylent',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
